### PR TITLE
Findup configuration

### LINKED ISSUE #4: Linting only works for files in the project root
Linting only works for files in the same directory as the configuration file `.php_cs`.

### PR DESCRIPTION
**Pull request by gerardroche**
Fixes #4 

Builds on top of https://github.com/jhoff/SublimeLinter-contrib-php-cs-fixer/pull/2 i.e. when you merge that PR this PR will be much easier to review.

### CODE REVIEW

**Comment by jhoff** [comment]
Sorry, I'm not experiencing the same issue as you've reported in #4 so I'm wondering what all of these changes are for. Can you break down what you're doing and why it's all needed?

**Comment by jhoff** [comment]
Reviewed and looks good. Thanks for the contribution!

**Comment by gerardroche** [comment]
> Sorry, I'm not experiencing the same issue as you've reported in #4 so I'm wondering what all of these changes are for. Can you break down what you're doing and why it's all needed?

Given that you merged, I assume after you reviewed the PR you understand the need for the findup functionality?

**Comment by jhoff** [comment]
Yeah, it made more sense once I broke it down.

**Pull request merged**
