### PR TITLE
Support for latest SublimeLinter and PHP CS Fixer v3.0

### LINKED ISSUE #10: Always see the status phpcsfixer(ok) and no error is highlighted
I've tried adding a new line before `<?php`, adding double semi-colons, and several other things I'd think would trigger it based on reading the `PHP-CS-Fixer` documentation and based on my experience with SublimeLinter for JavaScript.

Upon saving the file, nothing happens then either.

Any ideas?

### PR DESCRIPTION
**Pull request by gerardroche**
Support for latest SublimeLinter (fixes #10, #11, #12)
Support for php-cs-fixer v3.0 configuration

### CODE REVIEW

**Comment by braver** [comment]
Excellent, I was just looking for this. Currently the plugin won't work on the latest SL. @jhoff do you intend to pull this PR? Otherwise I intend to pull this repo into the SublimeLinter org so that it can be maintained by the community.

**Comment by braver** [comment]
@gerardroche I'm using php-cs-fixer 3.2.1 and it doesn't take `--diff-format` but `--diff` instead which outputs in udiff format.

**Comment by jhoff** [comment]
I just merged it. Not sure if there's anything else I need to do. It's been a while and I don't use sublime anymore.

Let me know if you need anything else. I'm happy to release it for community maintenance.

**Comment by gerardroche** [comment]
@braver @jhoff Yes, the --diff format changed in v3, I've been using a wip fix locally for a while. PR here https://github.com/jhoff/SublimeLinter-contrib-php-cs-fixer/pull/14

**Pull request merged**
